config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/confirm' => redirect("/")
  get 'home/thanks' => redirect("/")
  get "projects/index" => "projects#index"
  get "team/index" => "team#index"
  get "support/index" => "support#index"
  get "join/index" => "join#index"
  get "vrgame/index" => "vrgame#index"
  get "film/index" => "film#index"

  post "home/confirm" => "home#confirm"
  post "home/thanks" => "home#thanks"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  attr_accessor :name, :email, :subject, :message

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :subject, presence: true, length: {maximum: 300}
  validates :message, presence: true, length: {maximum: 1000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/film_controller.rb
class FilmController < ApplicationController

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(contact_params)
    if params[:back]
      render :action => 'index'
    else
      ContactMailer.received_email(@contact).deliver
      render :action => 'thanks'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :message)
    end
end

app/controllers/join_controller.rb
class JoinController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/support_controller.rb
class SupportController < ApplicationController

  def index
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end
end

app/controllers/vrgame_controller.rb
class VrgameController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/film_helper.rb
module FilmHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_helper.rb
module JoinHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/vrgame_helper.rb
module VrgameHelper
end

app/views/film/index.html.erb
<div class="film">
  <div class="black-background"></div>
  <div class="film-title">
    <p class="film-vertical">FILM</p>
  </div>
  <div class="content">
    <div class="view-container">
      <div class="film-container">
        <iframe src="https://player.vimeo.com/video/425557283" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
        <div class=visualising-epilepsy-title>
          <h2>Visualising Epilepsy</h2>
        </div>
      </div>
    </div>
    <div class="view-container">
      <div class="film-description-container">
        <div class="film-description-title">
          <h2>“What if you could experience a seizure?”</h2>
        </div>
        <div class="film-description">
          <p>A VR film promo that explores this question. Visualising Epilepsy presents two people who unknowingly enter an empty and mysterious area, where they discover a VR headset. Their curiosity takes over and they slowly discover that they are witnessing the auras of a focal and auditory seizure.</p>
          <p>When the distinction between reality and the virtual world blurs, they find themselves engulfed by the seizure as it takes control of their body. The outcome is a terrifying yet imaginative portrayal of how a seizure could appear inside your body...</p>
        </div>
      </div>
    </div>
    <div class="view-container relative">
      <div class="credit-container">
        <div class="credit-title">
          <h2>Credits</h2>
        </div>
        <div class="member-container">
          <div class="credit-member">
            <p class="credit-member-position"><b>Director</b></p>
            <p class="credit-member-name">Kezia Hessam</p>
          </div>
          <div class="credit-member">
            <p class="credit-member-position"><b>Director of Photography</b></p>
            <p class="credit-member-name">Michael Ryan Satria</p>
          </div>
          <div class="credit-member">
            <p class="credit-member-position"><b>Visual Effects Artist</b></p>
            <p class="credit-member-name">Sibel Gulbahce</p>
          </div>
          <div class="credit-member">
            <p class="credit-member-position"><b>Sound Designer</b></p>
            <p class="credit-member-name">Karl Richard</p>
          </div>
          <div class="credit-member">
            <p class="credit-member-position"><b>Performing Artists</b></p>
            <p class="credit-member-name">Thandie Van Wesenbeeck</p>
            <p class="credit-member-name">Carlo Chirila</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/home/confirm.html.erb
<!----------下記コンタクトフォームが機能するかテストするための仮コード---------->
<div class="page-header">
  <h1>問い合わせ確認画面</h1>
</div>

<%= form_with model: @contact, :url => home_thanks_path, local: true do |form| %>
  <table class="table">
    <tr>
      <th>Email:</th>
      <td>
        <%= form.hidden_field :email %>
        <%= @contact.email %>
      </td>
    </tr>

    <tr>
      <th>Name:</th>
      <td>
        <%= form.hidden_field :name %>
        <%= @contact.name %>
      </td>
    </tr>

    <tr>
      <th>subject</th>
      <td>
        <%= form.hidden_field :subject %>
        <%= @contact.subject %>
      </td>
    </tr>

    <tr>
      <th>Message:</th>
      <td>
        <%= form.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
  <%= form.submit 'Send', :class => 'btn btn-primary' %>
<% end %>
<!----------仮コードここまで---------->

app/views/home/index.html.erb
<!--<main>-->
  <div class="main-content">
    <div class="black-background"></div>
    <video class="home-background-video" src="https://dl.dropboxusercontent.com/s/avwfyb16s8g0waq/homepage_loop.mp4" autoplay loop muted></video>
    <div class="content main-contents">
      <div class="upper-contents">
        <div class="bubbles left-bubble">
          <a href="/support/index"><img class="bubble-image bubble-1" src="https://dl.dropboxusercontent.com/s/vllm6hghja6143b/support_button.png" alt=""></a>
        </div>
        <div class="bubbles center-bubble">
          <a href="/join/index"><img class="bubble-image bubble-2" src="https://dl.dropboxusercontent.com/s/nswtz0gih79ab5p/join_button.png" alt=""></a>
        </div>
        <div class="bubbles right-bubble">
          <a href="/team/index"><img class="bubble-image bubble-3" src="https://dl.dropboxusercontent.com/s/5wsf6jno1380hx5/about_button.png" alt=""></a>
        </div>
      </div>
      <div class="lower-contents"></div>
    </div>
  </div>
  <div class="black-block">
    <div class="black-block-container">
      <p class="scroll_fade fade_off">Welcome to the mind.</p>
    </div>
  </div>
  <div class="virtual-reality">
    <div class="black-background"></div>
    <div class="our-expertise-right">
      <p class="our-expertise-vertical">OUR EXPERTISE</p>
    </div>
    <div class="sub-content">
      <div class="explore-section">
        <!--<img src="https://dl.dropboxusercontent.com/s/lso5ltb5ejojzfu/vr_boy_bg.png" alt="">-->
        <a href="/vrgame/index"><h2>EXPLORE</h2></a>
      </div>
      <div class="our-expertise-description-section">
        <div class="our-expertise-description">
          <h2>The virtual escapism you’ve been searching for.</h2>
          <p>Alterscape is a collective dedicated to education through digital art media. We design and engineer experiential programmes using interactive virtual reality play-throughs that emulate neurological conditions.</p>
          <p>As a group, our specialities lie in VR/AR design, motion graphics, 3D imagery and storytelling. By marrying neurology, art and technology, our simulations take the viewer on an odyssey exploring the unique functions of the human body.</p>
        </div>
      </div>
    </div>
    <!--<div class="content">
      <div class="our-expertise-contents">
        <div class="our-expertise-content statement-left">
          <p class="our-vision-statement1">We imagine the world for you, so you no longer have to. Specialising in VR/AR design, motion graphics, 3D imagery and storytelling. Our artistry is dedicated to exploring
          </p>
        </div>
        <div class="our-expertise-content explore">
          <a href="/vrgame/index"><h1>EXPLORE</h1></a>
        </div>
        <div class="our-expertise-content statement-right">
          <p class="our-vision-statement2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec est felis. Duis sit amet libero vitae lorem pellentesque semper et id neque. Proin venenatis mauris tempus aliquam ullamcorper. Ut cursus sed massa vel sollicitudin. Donec nibh leo, consequat ut neque ac, malesuada volutpat turpis.
          </p>
        </div>
      </div>
    </div>-->
  </div>
  <!--<div class="black-block2">
    <p class="scroll_fade fade_off">We are the storytellers of the virtual world.</p>
  </div>-->
  <div class="black-block2">
    <div class="black-block-container">
      <p class="scroll_fade fade_off">We are the storytellers of the virtual world.</p>
    </div>
  </div>
  <div class="our-vision1">
    <div class="black-background"></div>
    <video class="purple-window-video" src="https://dl.dropboxusercontent.com/s/hvy5sc6s7nmussq/purple_window_bg.mp4" autoplay loop muted></video>
    <div class="our-vision-right">
      <p class="our-vision-vertical">OUR VISION</p>
    </div>
    <div class="sub-content">
      <div class="our-vision-contents">
        <h2>We imagine the world for you, so that you no longer have to.</h2>
        <div class="our-vision-statements">
          <p class="our-vision-statement1">Our goal is simple: to explore what is considered a negative product of our DNA and deliver beautiful outcomes. We describe our work as an accurately inaccurate portrayal of living with a neurological condition. We do not visualise conditions on a factual basis, instead we put it to the people to direct our work and we do so to perfection.</p>
        </div>
      </div>
      <div class="floating-button-container">
        <a href="/team/index"><img class="purple-button" src="https://dl.dropboxusercontent.com/s/co4c1958dr65ojb/learn_more_purple_door_button.png" ></a>
      </div>
    </div>
  </div>
  <!--<div class="purple-block">
    <p class="scroll_fade fade_off">Now is the time to discover.</p>
  </div>-->
  <div class="black-block2">
    <div class="black-block-container">
      <p class="scroll_fade fade_off">Now is the time to discover.</p>
    </div>
  </div>
  <div class="our-vision2">
    <div class="black-background"></div>
    <div class="our-vision2-right">
      <p class="our-vision2-vertical">OUR VISION</p>
    </div>
    <div class="sub-content">
      <div class="our-vision-contents">
        <h2>Pushing the boundaries of human intellect.</h2>
        <div class="our-vision-statements">
          <p class="our-vision-statement1">We exist to challenge our perception by questioning the extent of our present knowledge. On record, there are over 600 neurological conditions, affecting up to 1 billion people and counting. Experiential education in VR is now considered the new effective tool to engage with audiences. We want to reform public understanding through use of this technology to deliver artistic recreations of real life experiences, educating about first aid and spreading awareness of our biological differences.</p>
          <p>We aim to exceed medical knowledge and finally show people the real life stories of those who want their experiences visually expressed.</p>
        </div>
      </div>
      <div class="floating-button-container">
        <a href="/team/index"><img class="orange-button" src="https://dl.dropboxusercontent.com/s/pystnzxz3wxizvg/learnmore_brainbutton.png?" ></a>
      </div>
    </div>
  </div>
  <div id="contact">
    <div class="black-background"></div>
    <div class="contact-right">
      <p class="contact-vertical">CONTACT</p>
    </div>
    <div class="sub-content">
      <div class="contact-container"><!-----フォームができるまでtext-alignをセンターにする-->
        <div class="get-in-touch-section">
          <h2>Get in touch</h2>
          <p>We welcome diverse talent in our collective and are always on the lookout to work with new creatives from all walks of life.</p>
          <p>So whether you want to collaborate on a future project, share your experiences and ideas, or simply just speak with one of our team members, contact us today.</p>
          <p>We'd love to hear from you!<br><br><a href="mailto:hello@alterscapecollective.com">hello@alterscapecollective.com</a></p>
        </div>
        <!--<div class="contact-form-section">
          <%= form_with model: @contact, :url => home_confirm_path, local: true do |form| %>
            <% if @contact.errors.any? %>
              <div class="alert alert-warning">
                <ul>
                  <% @contact.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <%= form.email_field :email, :placeholder => "Email", class: "input-email" %>
            <%= form.text_field :name, :placeholder => "Name", class: "input-name" %>
            <%= form.text_field :subject, :placeholder => "Subject", class: "input-subject" %>
            <%= form.text_area :message, :placeholder => "Message...", class: "textarea-message" %>
            <%= form.submit "Confirm", class: "submit-send" %>
          <% end %>
        </div>-->
      </div>
    </div>
  </div>
<!--</main>-->
<%= render 'shared/footer' %>

app/views/home/thanks.html.erb
<div class="page-header">
  <h1>Message sent!</h1>
</div>
<p>
 Thank you for contacting us.<br>
 Your message was successfuly sent to Alterscape Collective team!
</p>

app/views/join/index.html.erb
<div class="join">
  <div class="join-container">
    <div class="join-title">
      <p class="join-vertical">JOIN</p>
    </div>
  </div>
  <div class="join-content">
    <div class="collaborate-with-us">
      <h2>Collaborate with us!</h2>
      <p>We are still a giant leap away from uncovering who we are and why we exist. We believe that our current knowledge doesn’t have to be limited to scientific study; creative technology has the potential to expand our understanding in hitherto undiscovered ways.</p>
    </div>
  </div>
</div>

<div class="why">
  <div class="black-background"></div>
  <div class="why-content">
    <div class="why-container">
      <h2>Why</h2>
      <p>We at Alterscape believe that collaboration is the best method to achieving the most precise and greatest results on any project. In the near future, we are getting ready to set up public immersive VR events and continuing our research into programming experiential play-throughs for the other 600 neurological conditions in the world.</p>
      <p>With teamwork comes more opportunities and endless possibilities. Our work is not literal, but it is daring. So feel no uncertainty in connecting with us as we endeavour to experiment and reach new heights.</p>
    </div>
  </div>
</div>

<div class="get-in-touch">
  <div class="black-background"></div>
  <video class="get-in-touch-video" src="https://dl.dropboxusercontent.com/s/yi0gw6vx6z0yneg/get_in_touch_bg.mp4" autoplay loop muted></video>
  <div class="dark-layer"></div>
  <div class="get-in-touch-content">
    <div class="get-in-touch-container">
      <h2>Enter our world</h2>
      <p>This is your opportunity to create because you can, and not because you’ve been asked to. Fill in our contact form or DM us on Instagram to join the experience.</p>
    </div>
    <div class="contact-button-container">
      <a href="/#contact"><p>Contact</p></a>
      <a href="https://www.instagram.com/alterscape_collective/" target="_blank"><p>Instagram</p></a>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>AlterscapeCollective</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="shortcut icon" href="../assets/TemplateData/favicon.ico">-->
    <!--<link rel="shortcut icon" href="https://dl.dropboxusercontent.com/s/sj8qxffptftohb0/alterscape_collective_footer_logo.png">-->
    <link rel="stylesheet" href="../WebGLGame/TemplateData/style.css">
    <!--<link rel="stylesheet" href="../assets/TemplateData/style.css">-->
    <script src="../WebGLGame/TemplateData/UnityProgress.js"></script>
    <!--<script src="../assets/TemplateData/UnityProgress.js"></script>-->
    <script src="../WebGLGame/Build/UnityLoader.js"></script>
    <!--<script src="../assets/Build/UnityLoader.js"></script>-->
    <!--<script>
      window.onload = function(){
        var unityInstance = UnityLoader.instantiate("unityContainer", "/WebGLGame/Build/AllScenes3.json", {onProgress: UnityProgress});
      }
    </script>-->
    <!--<script>
      var unityInstance = UnityLoader.instantiate("unityContainer", "../assets/Build/AllScenes3.json", {onProgress: UnityProgress});
    </script>-->
  </head>
  <body>
    <header>
      <div class="content">
        <div class="header-left">
          <a href="/"><img src="https://dl.dropboxusercontent.com/s/8l6bpeqa52hmdxa/logo-final%20copy-min.gif?dl=0" alt="ICON"></a>
        </div>
        <div class="header-centre">
          <a href="/">ALTERSCAPE COLLECTIVE</a>
        </div>
        <div class="header-right">
          <ul class="menu-list">
            <li class="menu_vr"><a href="/projects/index">PROJECTS</a></li>
            <li class="menu_list"><a href="/#contact">CONTACT</a></li>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="projects">
  <div class="black-background"></div>
  <div class="projects-right">
    <p class="projects-vertical">PROJECTS</p>
  </div>
  <div class="content">
    <div class="projects-container">
      <div class="projects-content upper-content">
        <div class="project-thumbnail">
          <h2><a href="/vrgame/index">Demystifying Epilepsy</a></h2>
          <a href="/vrgame/index"><video class="projects-thumbnail-video" poster="https://dl.dropboxusercontent.com/s/gbgobfv558n4q2i/poster_thumbnail1.png" src="https://dl.dropboxusercontent.com/s/uravz9kud9eknkf/projects_thumbnail1.mp4" loop></video></a>
          <!--<img src="../assets/vr_thumbnail1.png">-->
          <p>Enter an interactive virtual reality simulation that takes you through the stages of an epileptic seizure.
          </p>
        </div>
      </div>
      <div class="projects-content lower-content">
        <div class="project-thumbnail">
          <h2><a href="/film/index">Visualising Epilepsy</a></h2>
          <a href="/film/index"><video class="projects-thumbnail-video" poster="https://dl.dropboxusercontent.com/s/k6pkrgqcj6yjqpq/poster_thumbnail2.png" src="https://dl.dropboxusercontent.com/s/s94eux9g74f8bbh/projects_thumbnail2.mp4" loop></video></a>
          <!--<img src="../assets/vr_thumbnail2.png">-->
          <p>View a film performance piece that plays with the concept of experiencing an epileptic seizure through virtual reality.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-left">
    <img src="../assets/webstar_logo.png" alt="">
  </div>
  <!--<div class="footer-center">
    <ul class="footer-menues footer-menues-left">
      <li><a href="/support/index">DONATE</a></li>
      <li class="bordered-list"><a href="/join/index">JOIN</a></li>
    </ul>
    <a href=""><img src="../assets/alterscape_collective_footer_logo.png" alt=""></a>
    <ul class="footer-menues footer-menues-right">
      <li class="bordered-list"><a href="team/index">ABOUT</a></li>
      <li><a href="/projects/index">PROJECTS</a></li>
    </ul>
  </div>-->
  <div class="footer-center">
    <ul class="footer-menues">
      <li class="list-left footer-menu-list"><a href="/support/index">SUPPORT</a></li>
      <li class="footer-menu-list bordered-list"><a href="/join/index">JOIN</a></li>
      <li class="logo-list"><a href="/"><img src="https://dl.dropboxusercontent.com/s/sj8qxffptftohb0/alterscape_collective_footer_logo.png" alt=""></a></li>
      <li class="footer-menu-list bordered-list"><a href="/team/index">ABOUT</a></li>
      <li class="footer-menu-list"><a href="/projects/index">PROJECTS</a></li>
    </ul>
  </div>
  <div class="footer-right">
    <ul class="footer-logos">
      <li class="footer-logo"><a href="https://www.gofundme.com/f/epilepsy-action--purple-bench-initiative?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet" target="_blank"><img src="https://dl.dropboxusercontent.com/s/3f393rn5e621pfc/donate_icon.png"></a></li>
      <li class="footer-logo"><a href="https://vimeo.com/alterscapecollective" target="_blank"><img src="../assets/vimeo_logo.png"></a></li>
      <li class="footer-logo"><a href="https://www.instagram.com/alterscape_collective/" target="_blank"><img src="../assets/instagram_logo.png"></a></li>
    </ul>
    <p>© Alterscape Collective 2020</p>
  </div>
</footer>

app/views/support/index.html.erb
<div class="support">
  <div class="black-background"></div>
  <video class="support-bg-video" src="https://dl.dropboxusercontent.com/s/zyjoj7s4h5uzzuc/support_bg.mp4" width="100%" height="100%" autoplay loop muted></video>
  <div class="support-dark-layer"></div>
  <div class="support-container">
    <div class="support-title">
      <p class="support-vertical">SUPPORT</p>
    </div>
  </div>
  <div class="sub-content">
    <div class="donate-section">
      <h2 class="donate">Make a change</h2>
      <div class="donate-container">
        <div class="donate-description">
          <p>What we value most about our work is our contribution to health organisations and charities. As an NGO, we aren’t in this for the money, we are only interested in making positive changes within the community by improving health standards, first aid and most importantly, the well being of everyone.</p>
          <p>Every contribution, be it small or large, will go towards our selected charities. Bottom line: we want the lives of those who are suffering with an underlying neurological illness to live healthily and happily.</p>
          <!--<a href="#"><img src="../assets/give_today_button.png"></a>-->
        </div>
        <div class="give-today-section">
          <a href="https://www.gofundme.com/f/epilepsy-action--purple-bench-initiative?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet" target="_blank"><img src="https://dl.dropboxusercontent.com/s/q4kjbaunik1m7od/donate_button.png"></a>
        </div>
      </div>
    </div>
  </div>
</div>

  <!----------Bettering the community---------->
<div class="bettering-the-community">
  <div class="sub-content">
    <div class="stock-image-section">
      <img src="https://dl.dropboxusercontent.com/s/6wchouccaieauau/support_image.jpg">
    </div>
    <div class="bettering-the-community-description-section">
      <div class="bettering-the-community-description">
        <h2>Being better</h2>
        <p>Human existence is a mysterious one, and perhaps something we will never come to truly know. As advanced as medical technology is today, we still don’t fully understand these conditions. With no education being put in place to teach the public about these conditions either, we hope our efforts could make a great difference between saving or losing a life.</p>
        <p>For that reason our work is not only experiential, but educational in teaching others the triggers of brain abnormalities and how to react in an emergency situation.</p>
      </div>
    </div>
  </div>
</div>

<!-----------Our charities--------->
<div class="our-charities">
  <div class="sub-content">
    <div class="our-charities-upper-container">
      <div class="our-charities-description-container">
        <h2>Our charities</h2>
        <p>If you want to help us in our fight to improve medical support and education worldwide, please consider contributing to our current cause for these epilepsy charities:</p>
      </div>
    </div>
    <div class="our-charity-content our-charity1">
      <div class="charity-logo-container">
        <a href="https://www.epilepsy.org.uk/" target="_blank"><img src="https://dl.dropboxusercontent.com/s/6kcj0m52f2gsypf/epilepsy_action_logo.png"></a>
        <!--<a href="https://www.epilepsy.org.uk/" target="_blank"><h2>Epilepsy Action</h2></a>-->
      </div>
      <div class="our-charity-description our-charity-description2">
        <p>Helping the UK community by bettering the lives of those affected by epilepsy. Their goal is to improve healthcare services, research into pharmaceutical drugs and increase awareness and understanding nationwide. One of their aims is to support video education for children.</p>
      </div>
    </div>
    <div class="our-charity-content our-charity2">
      <div class="charity-logo-container">
        <a href="https://www.purplebenchug.org/" target="_blank"><img src="https://dl.dropboxusercontent.com/s/9bwci1eegdgrpv2/purple_bench_initiative_logo.png"></a>
        <!--<a href="https://www.purplebenchug.org/" target="_blank"><h2>Purple Bench Initiative</h2></a>-->
      </div>
      <div class="our-charity-description our-charity-description2">
        <p>A society where people living with epilepsy live a dignified, meaningful and highly impactful life.​ ​Every member of their community takes the responsibility to support people suffering from epilepsy at all times of need in order to enhance connections among People Living With Epilepsy.</p>
      </div>
    </div>
  </div>
</div>

<!----------Donate action---------->
<div class="donate-action">
  <div class="sub-content">
    <div class="question-section">
      <h2>We’re ready to make a difference, are you?</h2>
    </div>
    <div class="donate-button-section">
      <a href="https://www.gofundme.com/f/epilepsy-action--purple-bench-initiative?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet" target="_blank"><img src="https://dl.dropboxusercontent.com/s/q1ngp4nrv7sdtj1/give_today_button.png"></a>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>